plugins { id 'com.android.application' }
android {
    namespace 'com.jargo.neuralvpn'
    compileSdk 34
    defaultConfig {
        applicationId "com.jargo.neuralvpn"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    // 🔴 KUNCI ARSITEKTUR: Penunjukan absolut ke biner, membypass pemindaian dinamis
    implementation files('libs/core.aar')
}
