plugins { id 'com.android.application' }
android {
    namespace 'com.jargo.neuralvpn'
    compileSdk 34
    defaultConfig {
        applicationId "com.jargo.neuralvpn"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    // 🔴 INI KUNCI ARSITEKTUR: Membaca biner Golang (core.aar)
    implementation fileTree(dir: 'libs', include: ['*.aar'])
}
