name: Neural VPN APK Compiler

on:
  push:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Memuat Kode Sumber
      uses: actions/checkout@v4

    - name: 🔍 Verifikasi Biner (Diagnostik Matrix)
      run: |
        echo "Memeriksa brankas aset..."
        ls -lh android/app/src/main/assets/ || echo "Folder assets tidak ada!"
        if [ ! -s android/app/src/main/assets/core_engine ]; then
          echo "🔥 FATAL: Biner core_engine TIDAK ADA atau KOSONG di server Cloud!"
          exit 1
        fi
        echo "✅ Biner terdeteksi dengan sukses!"

    - name: ☕ Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 🔨 Kompilasi APK (Bypass Golang)
      run: |
        cd android
        gradle assembleDebug

    - name: 📦 Distribusi Artefak (APK)
      uses: actions/upload-artifact@v4
      with:
        name: Neural-VPN-App
        path: android/app/build/outputs/apk/debug/app-debug.apk
